name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3
    
    - name: Install PowerShell Core
      shell: powershell
      run: |
        winget install --id Microsoft.PowerShell --source winget --silent --accept-source-agreements --accept-package-agreements
    
    - name: Run Tests (No GUI Dependencies)
      shell: powershell
      run: |
        # Use build_tests_only.bat which doesn't require vcpkg (now located at root)
        .\build_tests_only.bat
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-windows
        path: |
          imgui_opengl_glad/build_tests/Testing/**/*.xml
          imgui_opengl_glad/build_tests/Testing/**/*.log

  build-and-test-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build pkg-config
        # Note: No GUI dependencies needed for tests-only build
    
    - name: Configure CMake (Tests Only)
      working-directory: imgui_opengl_glad
      run: |
        cmake -B build_tests -S . -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DWITH_IMGUI=OFF -G Ninja
    
    - name: Build Tests
      working-directory: imgui_opengl_glad
      run: |
        cmake --build build_tests --target unit_tests
    
    - name: Run Tests
      working-directory: imgui_opengl_glad
      run: |
        cd build_tests
        ctest --verbose --output-on-failure
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-linux
        path: |
          imgui_opengl_glad/build_tests/Testing/**/*.xml
          imgui_opengl_glad/build_tests/Testing/**/*.log

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format-14
    
    - name: Check code formatting
      run: |
        find imgui_opengl_glad -name "*.cpp" -o -name "*.h" | grep -E "(core|ui)" | xargs clang-format-14 --dry-run --Werror
    
    - name: Run static analysis (cppcheck)
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=warning,performance,portability --error-exitcode=1 imgui_opengl_glad/core/data_updater.cpp imgui_opengl_glad/core/data_updater.h
